ERROR - 2025-02-20 12:51:41 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u937000436_task'@'localhost' (using password: YES) in D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'u937000436_task', Object(SensitiveParameterValue), 'u937000436_task', NULL, '', 0)
#1 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Controllers\Home.php(34): App\Models\taskModel->getTasks()
#6 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(942): App\Controllers\Home->getTasks()
#7 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Controllers\Home.php(34): App\Models\taskModel->getTasks()
#5 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(942): App\Controllers\Home->getTasks()
#6 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2025-02-20 12:51:41 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tasks`
WHERE `Status` = :Status:', [...], false)
 3 APPPATH\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(34): App\Models\taskModel->getTasks()
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->getTasks()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 12:51:42 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u937000436_task'@'localhost' (using password: YES) in D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'u937000436_task', Object(SensitiveParameterValue), 'u937000436_task', NULL, '', 0)
#1 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Controllers\Home.php(34): App\Models\taskModel->getTasks()
#6 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(942): App\Controllers\Home->getTasks()
#7 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Controllers\Home.php(34): App\Models\taskModel->getTasks()
#5 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(942): App\Controllers\Home->getTasks()
#6 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2025-02-20 12:51:42 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tasks`
WHERE `Status` = :Status:', [...], false)
 3 APPPATH\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(34): App\Models\taskModel->getTasks()
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->getTasks()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 12:51:46 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u937000436_task'@'localhost' (using password: YES) in D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'u937000436_task', Object(SensitiveParameterValue), 'u937000436_task', NULL, '', 0)
#1 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Controllers\Home.php(34): App\Models\taskModel->getTasks()
#6 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(942): App\Controllers\Home->getTasks()
#7 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Controllers\Home.php(34): App\Models\taskModel->getTasks()
#5 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(942): App\Controllers\Home->getTasks()
#6 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2025-02-20 12:51:46 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tasks`
WHERE `Status` = :Status:', [...], false)
 3 APPPATH\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(34): App\Models\taskModel->getTasks()
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->getTasks()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 12:52:44 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u937000436_task'@'localhost' (using password: YES) in D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'u937000436_task', Object(SensitiveParameterValue), 'u937000436_task', NULL, '', 0)
#1 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Controllers\Home.php(34): App\Models\taskModel->getTasks()
#6 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(942): App\Controllers\Home->getTasks()
#7 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Controllers\Home.php(34): App\Models\taskModel->getTasks()
#5 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(942): App\Controllers\Home->getTasks()
#6 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2025-02-20 12:52:44 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tasks`
WHERE `Status` = :Status:', [...], false)
 3 APPPATH\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(34): App\Models\taskModel->getTasks()
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->getTasks()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 12:52:44 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u937000436_task'@'localhost' (using password: YES) in D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'u937000436_task', Object(SensitiveParameterValue), 'u937000436_task', NULL, '', 0)
#1 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Controllers\Home.php(34): App\Models\taskModel->getTasks()
#6 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(942): App\Controllers\Home->getTasks()
#7 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Controllers\Home.php(34): App\Models\taskModel->getTasks()
#5 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(942): App\Controllers\Home->getTasks()
#6 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2025-02-20 12:52:44 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tasks`
WHERE `Status` = :Status:', [...], false)
 3 APPPATH\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(34): App\Models\taskModel->getTasks()
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->getTasks()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 12:52:48 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u937000436_task'@'localhost' (using password: YES) in D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'u937000436_task', Object(SensitiveParameterValue), 'u937000436_task', NULL, '', 0)
#1 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Controllers\Home.php(34): App\Models\taskModel->getTasks()
#6 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(942): App\Controllers\Home->getTasks()
#7 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Controllers\Home.php(34): App\Models\taskModel->getTasks()
#5 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(942): App\Controllers\Home->getTasks()
#6 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2025-02-20 12:52:48 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tasks`
WHERE `Status` = :Status:', [...], false)
 3 APPPATH\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(34): App\Models\taskModel->getTasks()
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->getTasks()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 12:55:05 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u937000436_task'@'localhost' (using password: YES) in D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'u937000436_task', Object(SensitiveParameterValue), 'u937000436_task', NULL, '', 0)
#1 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Controllers\Home.php(34): App\Models\taskModel->getTasks()
#6 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(942): App\Controllers\Home->getTasks()
#7 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Controllers\Home.php(34): App\Models\taskModel->getTasks()
#5 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(942): App\Controllers\Home->getTasks()
#6 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2025-02-20 12:55:05 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tasks`
WHERE `Status` = :Status:', [...], false)
 3 APPPATH\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(34): App\Models\taskModel->getTasks()
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->getTasks()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 12:55:05 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u937000436_task'@'localhost' (using password: YES) in D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'u937000436_task', Object(SensitiveParameterValue), 'u937000436_task', NULL, '', 0)
#1 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Controllers\Home.php(34): App\Models\taskModel->getTasks()
#6 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(942): App\Controllers\Home->getTasks()
#7 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Controllers\Home.php(34): App\Models\taskModel->getTasks()
#5 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(942): App\Controllers\Home->getTasks()
#6 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2025-02-20 12:55:05 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tasks`
WHERE `Status` = :Status:', [...], false)
 3 APPPATH\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(34): App\Models\taskModel->getTasks()
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->getTasks()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 13:43:16 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u937000436_task'@'localhost' (using password: YES) in D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'u937000436_task', Object(SensitiveParameterValue), 'u937000436_task', NULL, '', 0)
#1 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Controllers\Home.php(34): App\Models\taskModel->getTasks()
#6 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(942): App\Controllers\Home->getTasks()
#7 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Controllers\Home.php(34): App\Models\taskModel->getTasks()
#5 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(942): App\Controllers\Home->getTasks()
#6 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2025-02-20 13:43:16 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tasks`
WHERE `Status` = :Status:', [...], false)
 3 APPPATH\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(34): App\Models\taskModel->getTasks()
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->getTasks()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 13:43:16 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u937000436_task'@'localhost' (using password: YES) in D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'u937000436_task', Object(SensitiveParameterValue), 'u937000436_task', NULL, '', 0)
#1 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Controllers\Home.php(34): App\Models\taskModel->getTasks()
#6 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(942): App\Controllers\Home->getTasks()
#7 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Controllers\Home.php(34): App\Models\taskModel->getTasks()
#5 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(942): App\Controllers\Home->getTasks()
#6 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2025-02-20 13:43:16 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tasks`
WHERE `Status` = :Status:', [...], false)
 3 APPPATH\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(34): App\Models\taskModel->getTasks()
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->getTasks()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 13:43:29 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u937000436_task'@'localhost' (using password: YES) in D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'u937000436_task', Object(SensitiveParameterValue), 'u937000436_task', NULL, '', 0)
#1 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Controllers\Home.php(34): App\Models\taskModel->getTasks()
#6 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(942): App\Controllers\Home->getTasks()
#7 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Controllers\Home.php(34): App\Models\taskModel->getTasks()
#5 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(942): App\Controllers\Home->getTasks()
#6 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2025-02-20 13:43:29 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tasks`
WHERE `Status` = :Status:', [...], false)
 3 APPPATH\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(34): App\Models\taskModel->getTasks()
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->getTasks()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 13:43:33 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u937000436_task'@'localhost' (using password: YES) in D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'u937000436_task', Object(SensitiveParameterValue), 'u937000436_task', NULL, '', 0)
#1 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Controllers\Home.php(34): App\Models\taskModel->getTasks()
#6 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(942): App\Controllers\Home->getTasks()
#7 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Controllers\Home.php(34): App\Models\taskModel->getTasks()
#5 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(942): App\Controllers\Home->getTasks()
#6 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2025-02-20 13:43:33 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tasks`
WHERE `Status` = :Status:', [...], false)
 3 APPPATH\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(34): App\Models\taskModel->getTasks()
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->getTasks()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 13:43:49 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u937000436_task'@'localhost' (using password: YES) in D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'u937000436_task', Object(SensitiveParameterValue), 'u937000436_task', NULL, '', 0)
#1 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Controllers\Home.php(34): App\Models\taskModel->getTasks()
#6 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(942): App\Controllers\Home->getTasks()
#7 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\app\Controllers\Home.php(34): App\Models\taskModel->getTasks()
#5 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(942): App\Controllers\Home->getTasks()
#6 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Programas Instalados\XAMPP\htdocs\2.-Tasks\TasksBack\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2025-02-20 13:43:49 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tasks`
WHERE `Status` = :Status:', [...], false)
 3 APPPATH\Models\taskModel.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(34): App\Models\taskModel->getTasks()
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->getTasks()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
